### ISSUE TITLE
Compiled bluescreens and precompiled works

### ISSUE THREAD

**Issue by fiujhjfsfsffgh** [cMiraka/Guarded-Regions-Bypass-Valorant#7]
Good source for learning & understanding. But i have the problem the everything is working with the precompiled Driver from the uc post but compiling it myself loading it and then starting the usermode application will result in a crash. Are there any settings that need to be done to make it compile correct?

**Comment by MaelOtin** [comment]
https://github.com/cMiraka/Guarded-Regions-Bypass-Valorant/issues/5
